# 设置tomcat端口,默认端口8080
server:
  port: 8080
# springboot配置mybatis连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2310956312
    driver-class-name: com.mysql.cj.jdbc.Driver
  # thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/   # 前缀
    suffix: .html                   # 后缀
    cache: false                    # 是否缓存(开发阶段不使用缓存, 线上开启)
    encoding: UTF-8                 # 编码
    mode: HTML5                     # 模式

# mybatis 配置
mybatis:
  type-aliases-package: com.softeem.springbootdemo.pojo # 配置别名包
  mapper-locations: classpath:mapper/*.xml              # 配置mapper.xml的位置

# 日志
logging:
  level:
    org.mybatis.spring.SqlSessionTemplate: DEBUG
    com.softeem.springbootdemo.mapper: DEBUG

# 分页插件配置
pagehelper:
  helperDialect: mysql # 数据库方言，默认为mysql
  reasonable: true # 启用合理化分页参数，默认false
  supportMethodsArguments: true # 支持通过 Mapper 接口参数来传递分页参数，默认false
  params: count=countSql # 用于 count 查询的 SQL 语句参数名称，默认为countSql
  page:
    size: 10 # 默认分页大小
    offset: 0 # 默认页码偏移量